version: '3.8'

services:
  app:
    build: .
    container_name: mi_tienda_app
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/mi_tienda
    networks:
      - tienda-network

  mongodb:
    image: mongo:6.0
    container_name: mi_tienda_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - tienda-network

  nginx:
    image: nginx:alpine
    container_name: mi_tienda_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - tienda-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - tienda-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - tienda-network

networks:
  tienda-network:
    driver: bridge

volumes:
  mongo-data:
